name: Building and Deploying .NET App to Azure Web App

on:
  push:
    branches:
      - main

env:
  AZURE_WEBAPP_NAME: course-management-system
  DOTNET_VERSION: "8.0.x"
  SOLUTION_PATH: "CourseManagementSystem.sln"
  API_PROJECT_PATH: "CourseManagementSystem"
  PUBLISH_DIR: "./publish"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore dependencies
        run: dotnet restore ${{ env.SOLUTION_PATH }}

      - name: Build
        run: dotnet build ${{ env.SOLUTION_PATH }} --configuration Release --no-restore

      - name: Publish app
        run: dotnet publish ${{ env.API_PROJECT_PATH }} --configuration Release --output ${{ env.PUBLISH_DIR }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEB_APP_COURSE_MANAGEMENT }}
          package: ${{ env.PUBLISH_DIR }}
