name: Build and Deploy .NET App to Azure Web App

on:
  push:
    branches:
      - main

env:
  AZURE_WEBAPP_NAME: ${{ secrets.AZURE_WEBAPP_NAME }}
  AZURE_PUBLISH_PROFILE: ${{ secrets.AZURE_PUBLISH_PROFILE }}
  DOTNET_VERSION: "8.0.x"
  SOLUTION_PATH: "CourseManagementSystem.sln"
  API_PROJECT_PATH: "CourseManagementSystem"
  PUBLISH_DIR: "./publish"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0.x"

      - name: Restore dependencies
        run: dotnet restore CourseManagementSystem.sln

      - name: Build
        run: dotnet build CourseManagementSystem.sln --configuration Release --no-restore

      - name: Publish
        run: dotnet publish CourseManagementSystem.sln --configuration Release --output ./publish

      - name: Azure Login
        uses: azure/login@v1
        with:
          public-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ env.AZURE_PUBLISH_PROFILE }}
          package: ./publish
